---
# Title slide
- "Pub Quiz"
- "Quiz paper sheets"
# Unknown category
- "Random"
# Open Trivia DB
- "General Knowledge"
- "Entertainment: Books"
- "Entertainment: Film"
- "Entertainment: Music"
- "Entertainment: Musicals & Theatres"
- "Entertainment: Television"
- "Entertainment: Video Games"
- "Entertainment: Board Games"
- "Science & Nature"
- "Science: Computers"
- "Science: Mathematics"
- "Mythology"
- "Sports"
- "Geography"
- "History"
- "Politics"
- "Art"
- "Celebrities"
- "Animals"
- "Vehicles"
- "Entertainment: Comics"
- "Science: Gadgets"
- "Entertainment: Japanese Anime & Manga"
- "Entertainment: Cartoon & Animations"
# The Trivia API
- "arts_and_literature"
- "film_and_tv"
- "food_and_drink"
- "general_knowledge"
- "geography"
- "history"
- "music"
- "science"
- "society_and_culture"
- "sport_and_leisure"
# QuizAPI
- "Linux"
- "bash"
- "uncategorized"
- "Docker"
- "SQL"
- "CMS"
- "Code"
- "DevOps"
# API Ninjas - Trivia
- "artliterature"
- "language"
- "sciencenature"
- "general"
- "fooddrink"
- "peopleplaces"
- "geography"
- "historyholidays"
- "entertainment"
- "toysgames"
- "music"
- "mathematics"
- "religionmythology"
- "sportsleisure"
...