---

# Base information for the API
BaseInfo:
  # Quiz title
  title: "Amazing Pyb Quiz"
  # Delay to use in seconds between API queries
  delay_api: 5
  # Extended verbose terminal output
  verbose: True
  # If True, update stats about remote DB (slow)
  clear_cache: False

# List of rounds
Rounds:
-
  # Title of the round
  title: "Round 1 - Linux"
  # Name of the library. Supported are : "opentriviadb", "thetriviaapi"
  api: "quizapi"
  # ID of the theme, see lookup table on top to know availability
  theme_id: 1
  # Difficulty level questions
  difficulty: [5, 3, 2]  # [num. of easy, num. of medium, num. of hard]
  # Type of questions. One of "text", or "image".
  type: "text"
-
  # Title of the round
  title: "Round 2 - Video Games"
  # Name of the library. Supported are : "opentriviadb", "thetriviaapi"
  api: "opentriviadb"
  # ID of the theme, see lookup table on top to know availability
  theme_id: 15
  # Difficulty level questions
  difficulty: [3, 3, 4]  # [num. of easy, num. of medium, num. of hard]
  # Type of questions. One of "text", or "image".
  type: "text"
-
  # Title of the round
  title: "Round 3 - Science"
  # Name of the library. Supported are : "opentriviadb", "thetriviaapi"
  api: "thetriviaapi"
  # ID of the theme, see lookup table on top to know availability
  theme_id: 7
  # Difficulty level questions
  difficulty: [2, 2, 6]  # [num. of easy, num. of medium, num. of hard]
  # Type of questions. One of "text", or "image".
  type: "text"
...