---

# Base information for the API
BaseInfo:
  # Delay to use in seconds between API queries
  delay_api: 5
  verbose: True

# List of rounds
Rounds:
-
  # Title of the round
  title: "Round 1 - Video Games"
  # Name of the library. Supported are : "opentriviadb", "thetriviaapi"
  api: "opentriviadb"
  # ID of the theme, see lookup table on top to know availability
  theme_id: 15
  # Difficulty level questions
  difficulty: [3, 3, 4]  # [num. of easy, num. of medium, num. of hard]
  # Type of questions. One of "text", or "image".
  type: "text"
-
  # Title of the round
  title: "Round 2 - Geography"
  # Name of the library. Supported are : "opentriviadb", "thetriviaapi"
  api: "thetriviaapi"
  # ID of the theme, see lookup table on top to know availability
  theme_id: 4
  # Difficulty level questions
  difficulty: [2, 4, 4]  # [num. of easy, num. of medium, num. of hard]
  # Type of questions. One of "text", or "image".
  type: "image"
  
...