---

# Base information for the API
BaseInfo:
  # Quiz title
  title: "Amazing Pyb Quiz"
  # Author
  author: "Your Quiz Master"
  # Delay to use in seconds between API queries
  delay_api: 5
  # Extended verbose terminal output
  verbose: True
  # If True, update stats about remote DB (slow)
  clear_cache: False

# List of rounds
Rounds:
-
  # Title of the round
  title: Mythology"
  # Name of the library
  api: "opentriviadb"
  # ID of the theme, see lookup table on top to know availability
  theme_id: 20
  # Difficulty level questions
  difficulty: [3, 3, 4]  # [num. of easy, num. of medium, num. of hard]
-
  # Title of the round
  title: "Geography"
  # Name of the library
  api: "opentriviadb"
  # ID of the theme, see lookup table on top to know availability
  theme_id: 22
  # Difficulty level questions
  difficulty: [3, 3, 4]  # [num. of easy, num. of medium, num. of hard]
-
  # Title of the round
  title: "Politics"
  # Name of the library
  api: "opentriviadb"
  # ID of the theme, see lookup table on top to know availability
  theme_id: 24
  # Difficulty level questions
  difficulty: [3, 3, 4]  # [num. of easy, num. of medium, num. of hard]
-
  # Title of the round
  title: "Film and TV"
  # Name of the library
  api: "thetriviaapi"
  # ID of the theme, see lookup table on top to know availability
  theme_id: 1
  # Difficulty level questions
  difficulty: [3, 3, 4]  # [num. of easy, num. of medium, num. of hard]
-
  # Title of the round
  title: "General Knowledge"
  # Name of the library
  api: "thetriviaapi"
  # ID of the theme, see lookup table on top to know availability
  theme_id: 3
  # Difficulty level questions
  difficulty: [3, 3, 4]  # [num. of easy, num. of medium, num. of hard]
...