---

# Base information for the API
BaseInfo:
  # Delay to use in seconds between API queries
  delay_api: 5
  verbose: True

# List of rounds
Rounds:
-
  # Title of the round
  title: "Round 1"
  # Name of the library. Supported are : "opentriviadb", "thetriviaapi"
  library: "opentriviadb"
  # ID of the theme, see lookup table on top to know availability
  theme: 13
  # Difficulty level questions
  difficulty: [3, 5, 1]  # [num. of easy, num. of medium, num. of hard]
  # Type of questions. One of "text", or "image".
  type: "text"

...